repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff lint
        entry: ./.venv/bin/ruff check src tests --select E9,F63,F7,F82 --ignore E501
        language: system
        types: [python]
        pass_filenames: false
