name: Model Evaluation

on:
  workflow_dispatch:

jobs:
  model-evaluate:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Evaluate model
        run: python src/model/model_evaluate.py